### ISSUE TITLE
 2 / output_count < 1 solution

### ISSUE THREAD

**Issue by usafphoenix** [Nanabell/Loader-Furnaces#5]
So i read your mod description and the woes with having a way to dynamically generate smelting recipes that fall within factorio crafts/per-tick limit.
this is a simple problem of using lcm, or lowest common multiple to determine what the input and output should be. 

the way we resolve it is to NOT require the output to always equal 2; we check first what the normal recipe is and then handle it one of two ways: either a) the way it's already handled, or b) in the event that the recipe would be broken (have the wrong number of ingredients:product ratio) then we use lcm (least common multiple) to determine the appropriate amount of resources / ingredients and the correct number of products for the resources required.

https://rosettacode.org/wiki/Least_common_multiple

**Comment by usafphoenix** [comment]
function gcd( m, n )
    while n ~= 0 do
        local q = m
        m = n
        n = q % n
    end
    return m
end
 
function lcm( m, n )
    return ( m ~= 0 and n ~= 0 ) and m * n / gcd( m, n ) or 0
end

**Comment by usafphoenix** [comment]
then determine a multiplier by dividing the larger value{m,n} by the lcm and multiply the ingredients and output by that.

**Comment by usafphoenix** [comment]
or another method is simply doubling both sides of the recipe:
ie, ingredient amounts are multiplied by 2, and the output_results are multiplied by 2. 
that may actually be the simpler solution...

**Comment by Nanabell** [comment]
Woah, totally didn't think about that. I knew to force the output to be 2 was going to cause issues but at that time I didn't really have a solution for it so I just went with it. 
Thanks  😄
