### ISSUE TITLE
Error when activating mod (String concatination)

### ISSUE THREAD

**Issue by SourceOverflow** [Nanabell/Loader-Furnaces#6]
In data.lua in line 16: `log('Found smelting recipe: "' + recipe.name + '"')` should probably be `log('Found smelting recipe: "' .. recipe.name .. '"')`

---

Full error report:
Error string provided by factorio at start-up:
__ Loader-Furncaces __/data.lua:16: attempt to perform arithmetic on a string value "Found smelting recipe:""

This happens with only the necessary mods activated:
Base Mod: 0.16.51
Loader Redux: 1.3.0
Loader Furnces: 3.0.1

**Comment by Nanabell** [comment]
huh, you're totally correct... 🤔 I wonder why it didn't fail for me. I've updated the latest master to use `..` instead of `+`. Could you do me a favor and replace both changed files in your instance and test if the problem is fixed for you?

**Comment by SourceOverflow** [comment]
I replaced both files and re-zipped it.
It is now loading fine :)

**Comment by Nanabell** [comment]
Perfect, Thank you then I will draft a new release and update the mod portal
