### ISSUE TITLE
Failed to load mods: _ _Loader-Furnaces_ _/data.lua:39: attempt to concatenate field 'anme' (a nil value)

### ISSUE THREAD

**Issue by VinnyWr** [Nanabell/Loader-Furnaces#8]
Fails to load. I'll provide a screenshot of the error and my mod list. Can't wait to be able to use this :) thank you for creating it.
![loaderfurnaces](https://user-images.githubusercontent.com/43010025/47260919-3c252a00-d479-11e8-8ca9-4b06f5f4b28e.PNG)
[mod-list.txt](https://github.com/Nanabell/Loader-Furnaces/files/2498598/mod-list.txt)

**Comment by Nanabell** [comment]
oh shit, that's a typo. Fixed gonna draft a new release now

**Comment by goakiller900** [comment]
Awsome thx

**Comment by VinnyWr** [comment]
Thank you very much! :D
